set OS_USERNAME=admin
set OS_PASSWORD=admin1234
set OS_PROJECT_NAME=admin
set OS_USER_DOMAIN_NAME=Default
set OS_PROJECT_DOMAIN_NAME=Default
set OS_AUTH_URL=http://controller:35357/v3
set OS_IDENTITY_API_VERSION=3
set OS_IMAGE_API_VERSION=2